version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/${USER}/data/nginx:/etc/nginx/conf.d
      - /home/${USER}/data/wordpress:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on :
      - wordpress
    networks:
      - my_network

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb
    networks:
      - my_network
    expose:
      - "9000"

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - /home/${USER}/data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - my_network
    expose:
      - "3306"

networks:
  my_network:
    driver: bridge
